### ISSUE TITLE
Use bwmon from another machine or on router without USB storage?

### ISSUE THREAD

**Issue by maphew** [VREMSoftwareDevelopment/bwmon#1]
My router, running Tomato 1.28, doesn't have the option to plug in a usb device for extra storage. 

a) Can bwmon be run on a separate machine and just fetch the necessary data from the router? What data files does it read/look for? I'm willing to hack together a curl or python script to fetch what is needed, if this is viable.

b) Is it possible to install and run bwmon in temporary nvram? I understand install and setup would have to repeated on every router power cycle.

This is a question not an issue, and might be out of scope. I was in the process of researching what I needed to do in order to write my own usage reporting service (probably badly!) and found your work, that does almost everything I want already. Thanks in advance for your thoughts and consideration.

**Comment by VREMSoftwareDevelopment** [comment]
Since bwmon server script is using Linux firewall, it would be hard to fetch remotely the necessary data from the router. 

The running data file is bwmonUsage.db. Take a look in [bwmon.sh](https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server/bwmon.sh) for format of the file.
The result file used by UI is [bwmonUsage.js](https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/app/bwmonUsage.js).

Yes it is possible to install and run bwmon in temporary nvram in tomato, it is [JFFS Partition](http://tomatousb.org/doc:jffs). And yes it will need to be installed on every router power cycle.  There are other issues like: the application might run out of space to store the data and you will lose collected data on very power cycle.

A network share from another computer on your LAN would probably be a easier solution. Here is [article](http://www.howtogeek.com/74881/how-to-monitor-and-log-your-bandwidth-usage-with-tomato/) that may be helpful for you to start on this solution.

If you are willing to expand and improve the application it would be great to have another contributor to the project.

**Comment by maphew** [comment]
Thank you for the advice. I'll come back after I've had a chance to ingest and experiment with it.My developer skills are pretty small, but I'll certainly contribute in any way that I can.

**Comment by maphew** [comment]
I reflashed my router with a build that had the samba client built in, and from there it was pretty straightforward to link to and install from a windows share. (I had delayed trying this for weeks because getting Tomato running the first time took so long with many false starts. I needn't have worried. Only took 3 minutes, apparently an upgrade is easier than fresh. ;-)

The Geek How-To article is pretty comprehensive. Main extra thing I had to do was create a dedicated Windows user for the router share. Guest account did not work even when password enabled. Then [Hide user from logon screen](http://www.mydigitallife.info/how-to-create-hidden-user-account-hide-user-account-from-welcome-screen-in-windows/)
